In [51]:
#Decision Tree Analysis for Classification
#https://stackabuse.com/decision-trees-in-python-with-scikit-learn/
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [52]:
dataset = pd.read_csv("data_test_two.csv")

In [53]:
dataset.shape

(1000, 31)

In [54]:
dataset.head()

Filename  Chromagram  RootMeanSquare  LowEnergyBrightness  \
0  blues.00000.wav    0.308240        0.082484            27.461745   
1  blues.00001.wav    0.301362        0.064603            27.914919   
2  blues.00002.wav    0.296246        0.121445            28.715256   
3  blues.00003.wav    0.378577        0.117733            27.093797   
4  blues.00004.wav    0.261497        0.060894            28.869262   

   SpectralCentroid  Flatness    Bandwidth  InHarmonicity      Rolloff  \
0       1530.180434  0.001002  1824.429264       0.001347  3168.064176   
1       1175.096777  0.000376  1712.769659       0.018918  2418.127045   
2       1300.687993  0.000450  1573.146791       0.023695  2474.635036   
3        763.311989  0.000145  1282.633866       0.003308  1384.558294   
4       1537.410063  0.000794  1578.964166      -0.049976  2951.473820   

   ZeroCrossingRate  ...      mfcc12    mfcc13     mfcc14     mfcc15  \
0          0.070382  ...    6.820536  0.147667   4.328625  -1.665351   
1          0.044440  ...    2.653106  0.852110   2.218112  -4.896205   
2          0.064787  ...    4.730809 -7.923660  -5.274928  -8.546422   
3          0.024863  ...    5.116895  0.443054  -1.879724   0.222495   
4          0.085609  ...   -6.884247 -6.812018 -12.432060 -10.807361   

     mfcc16    mfcc17    mfcc18    mfcc19     mfcc20  label  
0 -1.945349  0.523056 -2.841816 -0.065698  -0.999933  blues  
1 -1.090712  1.080965 -0.705705  1.682992  -0.814985  blues  
2  0.367640 -7.297458 -4.841222 -3.672829  -4.288005  blues  
3  1.200053 -0.744148  1.804096 -0.031980  -4.040267  blues  
4 -8.185105 -5.412588 -1.941454 -7.050840 -17.652891  blues  

[5 rows x 31 columns]

In [55]:
X = dataset.drop(['Filename','label'],axis=1) #Filename is not required
Y = dataset['label']

In [56]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.10)

In [57]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [58]:
Y_pred = classifier.predict(X_test)

In [59]:
#Have to remove filename and label for this to work and then point Y at the label for each
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

[[6 0 1 0 0 0 1 0 0 1]
 [0 9 0 0 0 1 0 0 0 0]
 [1 0 5 2 0 0 1 0 2 0]
 [0 0 0 7 0 0 0 0 1 1]
 [0 0 0 0 4 0 3 3 2 0]
 [0 1 0 0 1 4 0 0 0 1]
 [1 0 0 0 0 0 9 1 0 0]
 [1 1 1 1 3 2 0 6 0 0]
 [0 0 0 5 2 0 0 0 4 0]
 [0 0 1 0 0 0 0 0 0 4]]
              precision    recall  f1-score   support

       blues       0.67      0.67      0.67         9
   classical       0.82      0.90      0.86        10
     country       0.62      0.45      0.53        11
       disco       0.47      0.78      0.58         9
      hiphop       0.40      0.33      0.36        12
        jazz       0.57      0.57      0.57         7
       metal       0.64      0.82      0.72        11
         pop       0.60      0.40      0.48        15
      reggae       0.44      0.36      0.40        11
        rock       0.57      0.80      0.67         5

    accuracy                           0.58       100
   macro avg       0.58      0.61      0.58       100
weighted avg       0.58      0.58      0.57       100



In [60]:
#Decision Tree Analysis for Regression
dataset2 = pd.read_csv("data_test_two.csv")

In [61]:
dataset2

Filename  Chromagram  RootMeanSquare  LowEnergyBrightness  \
0    blues.00000.wav    0.308240        0.082484            27.461745   
1    blues.00001.wav    0.301362        0.064603            27.914919   
2    blues.00002.wav    0.296246        0.121445            28.715256   
3    blues.00003.wav    0.378577        0.117733            27.093797   
4    blues.00004.wav    0.261497        0.060894            28.869262   
5    blues.00005.wav    0.265523        0.078779            30.561682   
6    blues.00006.wav    0.254311        0.109664            30.890941   
7    blues.00007.wav    0.269021        0.099818            29.627338   
8    blues.00008.wav    0.372944        0.109156            28.785792   
9    blues.00009.wav    0.238587        0.063637            27.988616   
10   blues.00010.wav    0.260775        0.116048            28.643808   
11   blues.00011.wav    0.328286        0.055191            27.242355   
12   blues.00012.wav    0.234738        0.095073            29.228240   
13   blues.00013.wav    0.226230        0.092688            28.099401   
14   blues.00014.wav    0.310018        0.053512            28.776113   
15   blues.00015.wav    0.236322        0.056500            27.963895   
16   blues.00016.wav    0.266695        0.057444            27.520552   
17   blues.00017.wav    0.262490        0.072574            28.704377   
18   blues.00018.wav    0.243455        0.065755            28.426076   
19   blues.00019.wav    0.223666        0.073543            28.123479   
20   blues.00020.wav    0.262224        0.053997            26.276840   
21   blues.00021.wav    0.290386        0.079586            28.854573   
22   blues.00022.wav    0.272902        0.086330            29.090671   
23   blues.00023.wav    0.253112        0.079764            29.105515   
24   blues.00024.wav    0.235386        0.069181            28.859672   
25   blues.00025.wav    0.244809        0.069095            28.000193   
26   blues.00026.wav    0.254017        0.059309            29.348840   
27   blues.00027.wav    0.266204        0.078391            30.582220   
28   blues.00028.wav    0.245784        0.076353            28.289034   
29   blues.00029.wav    0.261466        0.112416            33.280868   
..               ...         ...             ...                  ...   
970   rock.00070.wav    0.321252        0.039313            32.105902   
971   rock.00071.wav    0.397564        0.098152            26.374552   
972   rock.00072.wav    0.351510        0.124012            27.939425   
973   rock.00073.wav    0.387420        0.113000            27.519898   
974   rock.00074.wav    0.340014        0.115370            28.776396   
975   rock.00075.wav    0.347508        0.080204            27.508045   
976   rock.00076.wav    0.306034        0.113132            30.051773   
977   rock.00077.wav    0.397017        0.087700            27.426899   
978   rock.00078.wav    0.320641        0.111608            29.524695   
979   rock.00079.wav    0.305343        0.083286            28.620341   
980   rock.00080.wav    0.316282        0.073007            29.207878   
981   rock.00081.wav    0.289125        0.065577            29.610781   
982   rock.00082.wav    0.328576        0.062061            29.251862   
983   rock.00083.wav    0.326889        0.077985            30.123382   
984   rock.00084.wav    0.297545        0.078222            29.343515   
985   rock.00085.wav    0.296341        0.051952            32.567357   
986   rock.00086.wav    0.329008        0.048373            27.827078   
987   rock.00087.wav    0.337058        0.125365            28.924663   
988   rock.00088.wav    0.337486        0.055793            27.360899   
989   rock.00089.wav    0.302035        0.079545            31.683559   
990   rock.00090.wav    0.216348        0.127356            29.501664   
991   rock.00091.wav    0.368251        0.079819            29.286965   
992   rock.00092.wav    0.333389        0.076316            29.743138 

In [44]:
dataset2.describe()

Chromagram  RootMeanSquare  LowEnergyBrightness  SpectralCentroid  \
count  1000.000000     1000.000000          1000.000000       1000.000000   
mean      0.333170        0.093429            26.858281       1751.852193   
std       0.068632        0.046011             3.124805        601.522888   
min       0.168503        0.004786            16.145770        439.129276   
25%       0.283503        0.060688            24.783428       1240.103400   
50%       0.332275        0.087042            26.764932       1758.225508   
75%       0.374445        0.122142            28.871451       2176.113692   
max       0.608037        0.282542            35.911892       4537.019858   

          Flatness    Bandwidth  InHarmonicity      Rolloff  ZeroCrossingRate  \
count  1000.000000  1000.000000    1000.000000  1000.000000       1000.000000   
mean      0.004795  1976.391038       0.002693  3690.915899          0.077059   
std       0.011511   490.293416       0.013064  1429.690844          0.032975   
min       0.000009   748.087477      -0.056817   643.521109          0.012361   
25%       0.000446  1614.056496      -0.005262  2460.870536          0.052362   
50%       0.001809  2025.381742       0.002928  3757.502279          0.072380   
75%       0.005397  2321.772532       0.011031  4713.833996          0.096995   
max       0.252005  3353.718981       0.042207  8025.718136          0.291544   

             mfcc1     ...            mfcc11       mfcc12       mfcc13  \
count  1000.000000     ...       1000.000000  1000.000000  1000.000000   
mean   -214.423790     ...         -6.419502     5.724268    -5.402651   
std      93.303535     ...          6.783498     7.294746     6.420117   
min    -595.157104     ...        -34.519875   -17.169533   -29.783953   
25%    -269.700760     ...        -11.323158     0.651697    -9.880047   
50%    -195.321487     ...         -6.648439     6.013866    -5.793390   
75%    -145.536682     ...         -2.162718    11.095165    -1.196022   
max     -36.345001     ...         16.976814    24.150690    14.146593   

            mfcc14       mfcc15       mfcc16       mfcc17       mfcc18  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean      2.496866    -4.625561     1.617107    -4.803964     0.879838   
std       6.137700     5.561395     5.900692     5.422455     5.616104   
min     -16.076685   -21.920017   -18.993584   -21.908558   -15.023964   
25%      -1.666956    -8.316156    -1.935053    -8.429702    -2.727615   
50%       2.518728    -4.950700     1.733292    -5.267792     0.763764   
75%       6.803452    -1.027034     5.470085    -1.474443     4.278270   
max      20.033194    16.499084    22.298786    17.950909    23.989403   

            mfcc19       mfcc20  
count  1000.000000  1000.000000  
mean     -2.998892    -1.197808  
std       4.897290     5.737915  
min     -20.534409   -25.400860  
25%      -6.121026    -4.936768  
50%      -3.108214    -1.565663  
75%       0.017796     2.212895  
max      25.946220    22.816999  

[8 rows x 29 columns]

In [45]:
X = dataset2.drop(['Filename','label'],axis=1) #Filename is not required
Y = dataset2['Chromagram'] 
#Has to be a float number for this type of decision tree otherwise use label

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.10, random_state=0)

In [47]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor()
regressor.fit(X_train, Y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [48]:
Y_pred = regressor.predict(X_test)

In [49]:
df=pd.DataFrame({'Actual':Y_test, 'Predicted':Y_pred})
df

Actual  Predicted
993  0.297712   0.297386
859  0.322412   0.322253
298  0.250067   0.250387
553  0.288828   0.288875
672  0.393069   0.392220
971  0.397564   0.397783
27   0.266204   0.265546
231  0.289715   0.290311
306  0.380803   0.381091
706  0.336237   0.336841
496  0.375372   0.375336
558  0.299664   0.299472
784  0.323314   0.323413
239  0.381732   0.382285
578  0.245149   0.245990
55   0.365651   0.366005
906  0.299356   0.299472
175  0.210523   0.210983
14   0.310018   0.310269
77   0.349827   0.350199
31   0.243690   0.243544
481  0.423724   0.419765
310  0.370530   0.370373
311  0.325989   0.326287
883  0.309942   0.310269
788  0.347111   0.347792
45   0.394427   0.395087
103  0.228261   0.228864
760  0.344267   0.344091
1    0.301362   0.300977
..        ...        ...
738  0.336075   0.335615
299  0.327101   0.326962
740  0.268862   0.269121
247  0.278839   0.279314
926  0.315761   0.316289
412  0.314920   0.315148
389  0.370105   0.370373
796  0.313866   0.313843
601  0.401239   0.400825
654  0.437337   0.435164
261  0.292509   0.292591
456  0.429847   0.429813
386  0.345626   0.345729
982  0.328576   0.328710
909  0.339080   0.338780
693  0.340079   0.340176
236  0.322613   0.322253
501  0.282486   0.283184
497  0.457217   0.459737
874  0.442384   0.442640
452  0.418371   0.416567
494  0.475771   0.475611
923  0.256639   0.255271
279  0.287184   0.287162
638  0.395258   0.395087
485  0.461834   0.466151
568  0.268026   0.268179
108  0.243176   0.242733
367  0.293939   0.294201
644  0.416651   0.416567

[100 rows x 2 columns]

In [50]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(Y_test, Y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(Y_test, Y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(Y_test, Y_pred)))

Mean Absolute Error: 0.0005489967990489212
Mean Squared Error: 8.685589352530463e-07
Root Mean Squared Error: 0.0009319650933661874
