In [2]:
#Decision Tree Analysis for Classification
#https://stackabuse.com/decision-trees-in-python-with-scikit-learn/
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
dataset = pd.read_csv("data_test_two.csv")

In [3]:
dataset.shape

(1000, 31)

In [4]:
dataset.head()

Filename  Chromagram  RootMeanSquare  LowEnergyBrightness  \
0    blues.00000.wav    0.308240        0.082484            27.461745   
1    blues.00001.wav    0.301362        0.064603            27.914919   
2    blues.00002.wav    0.296246        0.121445            28.715256   
3    blues.00003.wav    0.378577        0.117733            27.093797   
4    blues.00004.wav    0.261497        0.060894            28.869262   
..               ...         ...             ...                  ...   
995   rock.00095.wav    0.312390        0.066186            30.688717   
996   rock.00096.wav    0.346445        0.060734            30.686908   
997   rock.00097.wav    0.366349        0.060549            30.018262   
998   rock.00098.wav    0.327993        0.071812            29.785034   
999   rock.00099.wav    0.335972        0.049566            32.204049   

     SpectralCentroid  Flatness    Bandwidth  InHarmonicity      Rolloff  \
0         1530.180434  0.001002  1824.429264       0.001347  3168.064176   
1         1175.096777  0.000376  1712.769659       0.018918  2418.127045   
2         1300.687993  0.000450  1573.146791       0.023695  2474.635036   
3          763.311989  0.000145  1282.633866       0.003308  1384.558294   
4         1537.410063  0.000794  1578.964166      -0.049976  2951.473820   
..                ...       ...          ...            ...          ...   
995       1581.409638  0.000851  1869.828399      -0.023475  3382.146215   
996       1681.291780  0.001022  1862.853262      -0.012933  3389.512837   
997       1804.013421  0.001316  1780.175455      -0.002448  3556.861825   
998       1043.976973  0.000185  1540.514360       0.022385  2149.253670   
999       1336.378480  0.000376  1587.193198       0.031731  2675.450489   

     ZeroCrossingRate  ...     mfcc12     mfcc13     mfcc14     mfcc15  \
0            0.070382  ...   6.820536   0.147667   4.328625  -1.665351   
1            0.044440  ...   2.653106   0.852110   2.218112  -4.896205   
2            0.064787  ...   4.730809  -7.923660  -5.274928  -8.546422   
3            0.024863  ...   5.116895   0.443054  -1.879724   0.222495   
4            0.085609  ...  -6.884247  -6.812018 -12.432060 -10.807361   
..                ...  ...        ...        ...        ...        ...   
995          0.066453  ...  10.248952 -10.964746   2.161331  -8.731913   
996          0.079978  ...  12.340167 -15.811428   2.499770  -1.465077   
997          0.103779  ...   7.016281 -16.999731  -3.583634 -11.462903   
998          0.036334  ...   5.101926  -8.858630  -3.481705  -4.420999   
999          0.065614  ...   8.735400 -14.038234   0.994078  -6.311344   

       mfcc16     mfcc17    mfcc18     mfcc19     mfcc20  label  
0   -1.945349   0.523056 -2.841816  -0.065698  -0.999933  blues  
1   -1.090712   1.080965 -0.705705   1.682992  -0.814985  blues  
2    0.367640  -7.297458 -4.841222  -3.672829  -4.288005  blues  
3    1.200053  -0.744148  1.804096  -0.031980  -4.040267  blues  
4   -8.185105  -5.412588 -1.941454  -7.050840 -17.652891  blues  
..        ...        ...       ...        ...        ...    ...  
995 -1.181509 -12.371817  0.345473  -4.355881  -3.619780   rock  
996  0.332790 -10.561275 -1.007160  -6.957969  -6.305751   rock  
997 -2.264517 -12.694439 -0.091419 -12.558615  -6.974419   rock  
998 -5.908291  -2.952532  0.013109  -4.228845  -5.788094   rock  
999 -0.421449  -5.856144 -1.394981  -0.071674   1.036793   rock  

[1000 rows x 31 columns]

In [5]:
X = dataset.drop(['Filename','label'],axis=1) #Filename is not required
Y = dataset['label']

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.10)

In [7]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [8]:
Y_pred = classifier.predict(X_test)

In [9]:
#Have to remove filename and label for this to work and then point Y at the label for each
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

[[ 7  0  0  0  0  0  0  0  1  0]
 [ 0 11  1  0  0  1  0  0  0  0]
 [ 0  1  7  0  1  1  0  1  1  0]
 [ 0  1  1  5  0  0  0  2  1  1]
 [ 0  0  0  2  4  0  1  1  1  0]
 [ 2  0  0  0  0  3  0  1  0  0]
 [ 0  0  0  0  0  0 11  0  0  0]
 [ 0  1  1  0  1  0  1  6  1  2]
 [ 1  0  0  1  0  0  0  0  8  0]
 [ 1  1  0  0  1  0  0  1  0  3]]
              precision    recall  f1-score   support

       blues       0.64      0.88      0.74         8
   classical       0.73      0.85      0.79        13
     country       0.70      0.58      0.64        12
       disco       0.62      0.45      0.53        11
      hiphop       0.57      0.44      0.50         9
        jazz       0.60      0.50      0.55         6
       metal       0.85      1.00      0.92        11
         pop       0.50      0.46      0.48        13
      reggae       0.62      0.80      0.70        10
        rock       0.50      0.43      0.46         7

    accuracy                           0.65       100
   macro avg       

In [3]:
#Decision Tree Analysis for Regression
dataset2 = pd.read_csv("data_test_two.csv")

In [4]:
dataset2

Filename  Chromagram  RootMeanSquare  LowEnergyBrightness  \
0    blues.00000.wav    0.308240        0.082484            27.461745   
1    blues.00001.wav    0.301362        0.064603            27.914919   
2    blues.00002.wav    0.296246        0.121445            28.715256   
3    blues.00003.wav    0.378577        0.117733            27.093797   
4    blues.00004.wav    0.261497        0.060894            28.869262   
..               ...         ...             ...                  ...   
995   rock.00095.wav    0.312390        0.066186            30.688717   
996   rock.00096.wav    0.346445        0.060734            30.686908   
997   rock.00097.wav    0.366349        0.060549            30.018262   
998   rock.00098.wav    0.327993        0.071812            29.785034   
999   rock.00099.wav    0.335972        0.049566            32.204049   

     SpectralCentroid  Flatness    Bandwidth  InHarmonicity      Rolloff  \
0         1530.180434  0.001002  1824.429264       0.001347  3168.064176   
1         1175.096777  0.000376  1712.769659       0.018918  2418.127045   
2         1300.687993  0.000450  1573.146791       0.023695  2474.635036   
3          763.311989  0.000145  1282.633866       0.003308  1384.558294   
4         1537.410063  0.000794  1578.964166      -0.049976  2951.473820   
..                ...       ...          ...            ...          ...   
995       1581.409638  0.000851  1869.828399      -0.023475  3382.146215   
996       1681.291780  0.001022  1862.853262      -0.012933  3389.512837   
997       1804.013421  0.001316  1780.175455      -0.002448  3556.861825   
998       1043.976973  0.000185  1540.514360       0.022385  2149.253670   
999       1336.378480  0.000376  1587.193198       0.031731  2675.450489   

     ZeroCrossingRate  ...     mfcc12     mfcc13     mfcc14     mfcc15  \
0            0.070382  ...   6.820536   0.147667   4.328625  -1.665351   
1            0.044440  ...   2.653106   0.852110   2.218112  -4.896205   
2            0.064787  ...   4.730809  -7.923660  -5.274928  -8.546422   
3            0.024863  ...   5.116895   0.443054  -1.879724   0.222495   
4            0.085609  ...  -6.884247  -6.812018 -12.432060 -10.807361   
..                ...  ...        ...        ...        ...        ...   
995          0.066453  ...  10.248952 -10.964746   2.161331  -8.731913   
996          0.079978  ...  12.340167 -15.811428   2.499770  -1.465077   
997          0.103779  ...   7.016281 -16.999731  -3.583634 -11.462903   
998          0.036334  ...   5.101926  -8.858630  -3.481705  -4.420999   
999          0.065614  ...   8.735400 -14.038234   0.994078  -6.311344   

       mfcc16     mfcc17    mfcc18     mfcc19     mfcc20  label  
0   -1.945349   0.523056 -2.841816  -0.065698  -0.999933  blues  
1   -1.090712   1.080965 -0.705705   1.682992  -0.814985  blues  
2    0.367640  -7.297458 -4.841222  -3.672829  -4.288005  blues  
3    1.200053  -0.744148  1.804096  -0.031980  -4.040267  blues  
4   -8.185105  -5.412588 -1.941454  -7.050840 -17.652891  blues  
..        ...        ...       ...        ...        ...    ...  
995 -1.181509 -12.371817  0.345473  -4.355881  -3.619780   rock  
996  0.332790 -10.561275 -1.007160  -6.957969  -6.305751   rock  
997 -2.264517 -12.694439 -0.091419 -12.558615  -6.974419   rock  
998 -5.908291  -2.952532  0.013109  -4.228845  -5.788094   rock  
999 -0.421449  -5.856144 -1.394981  -0.071674   1.036793   rock  

[1000 rows x 31 columns]

In [5]:
dataset2.describe()

Chromagram  RootMeanSquare  LowEnergyBrightness  SpectralCentroid  \
count  1000.000000     1000.000000          1000.000000       1000.000000   
mean      0.333170        0.093429            26.858281       1751.852193   
std       0.068632        0.046011             3.124805        601.522888   
min       0.168503        0.004786            16.145770        439.129276   
25%       0.283503        0.060688            24.783428       1240.103400   
50%       0.332275        0.087042            26.764932       1758.225508   
75%       0.374445        0.122142            28.871451       2176.113692   
max       0.608037        0.282542            35.911892       4537.019858   

          Flatness    Bandwidth  InHarmonicity      Rolloff  ZeroCrossingRate  \
count  1000.000000  1000.000000    1000.000000  1000.000000       1000.000000   
mean      0.004795  1976.391038       0.002693  3690.915899          0.077059   
std       0.011511   490.293416       0.013064  1429.690844          0.032975   
min       0.000009   748.087477      -0.056817   643.521109          0.012361   
25%       0.000446  1614.056496      -0.005262  2460.870536          0.052362   
50%       0.001809  2025.381742       0.002928  3757.502279          0.072380   
75%       0.005397  2321.772532       0.011031  4713.833996          0.096995   
max       0.252005  3353.718981       0.042207  8025.718136          0.291544   

             mfcc1  ...       mfcc11       mfcc12       mfcc13       mfcc14  \
count  1000.000000  ...  1000.000000  1000.000000  1000.000000  1000.000000   
mean   -214.423790  ...    -6.419502     5.724268    -5.402651     2.496866   
std      93.303535  ...     6.783498     7.294746     6.420117     6.137700   
min    -595.157104  ...   -34.519875   -17.169533   -29.783953   -16.076685   
25%    -269.700760  ...   -11.323158     0.651697    -9.880047    -1.666956   
50%    -195.321487  ...    -6.648439     6.013866    -5.793390     2.518728   
75%    -145.536682  ...    -2.162718    11.095165    -1.196022     6.803452   
max     -36.345001  ...    16.976814    24.150690    14.146593    20.033194   

            mfcc15       mfcc16       mfcc17       mfcc18       mfcc19  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean     -4.625561     1.617107    -4.803964     0.879838    -2.998892   
std       5.561395     5.900692     5.422455     5.616104     4.897290   
min     -21.920017   -18.993584   -21.908558   -15.023964   -20.534409   
25%      -8.316156    -1.935053    -8.429702    -2.727615    -6.121026   
50%      -4.950700     1.733292    -5.267792     0.763764    -3.108214   
75%      -1.027034     5.470085    -1.474443     4.278270     0.017796   
max      16.499084    22.298786    17.950909    23.989403    25.946220   

            mfcc20  
count  1000.000000  
mean     -1.197808  
std       5.737915  
min     -25.400860  
25%      -4.936768  
50%      -1.565663  
75%       2.212895  
max      22.816999  

[8 rows x 29 columns]

In [6]:
X = dataset2.drop(['Filename','label'],axis=1) #Filename is not required
Y = dataset2['Chromagram'] 
#Has to be a float number for this type of decision tree otherwise use label

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.10, random_state=0)

In [8]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor()
regressor.fit(X_train, Y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [9]:
Y_pred = regressor.predict(X_test)

In [10]:
df=pd.DataFrame({'Actual':Y_test, 'Predicted':Y_pred})
df

Actual  Predicted
993  0.297712   0.297386
859  0.322412   0.322253
298  0.250067   0.250387
553  0.288828   0.288875
672  0.393069   0.392220
..        ...        ...
485  0.461834   0.466151
568  0.268026   0.268179
108  0.243176   0.242733
367  0.293939   0.294201
644  0.416651   0.416567

[100 rows x 2 columns]

In [11]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(Y_test, Y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(Y_test, Y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(Y_test, Y_pred)))

Mean Absolute Error: 0.0005231286837231541
Mean Squared Error: 6.977468879225878e-07
Root Mean Squared Error: 0.0008353124492802605
