In [1]:
import pandas as pd
import numpy as np

import sklearn
from sklearn.preprocessing import StandardScaler, normalize 
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
dataset = pd.read_csv("data_test_two.csv")

In [3]:
dataset.shape

(1000, 31)

In [4]:
dataset.head()

Filename  Chromagram  RootMeanSquare  LowEnergyBrightness  \
0  blues.00000.wav    0.308240        0.082484            27.461745   
1  blues.00001.wav    0.301362        0.064603            27.914919   
2  blues.00002.wav    0.296246        0.121445            28.715256   
3  blues.00003.wav    0.378577        0.117733            27.093797   
4  blues.00004.wav    0.261497        0.060894            28.869262   

   SpectralCentroid  Flatness    Bandwidth  InHarmonicity      Rolloff  \
0       1530.180434  0.001002  1824.429264       0.001347  3168.064176   
1       1175.096777  0.000376  1712.769659       0.018918  2418.127045   
2       1300.687993  0.000450  1573.146791       0.023695  2474.635036   
3        763.311989  0.000145  1282.633866       0.003308  1384.558294   
4       1537.410063  0.000794  1578.964166      -0.049976  2951.473820   

   ZeroCrossingRate  ...      mfcc12    mfcc13     mfcc14     mfcc15  \
0          0.070382  ...    6.820536  0.147667   4.328625  -1.665351   
1          0.044440  ...    2.653106  0.852110   2.218112  -4.896205   
2          0.064787  ...    4.730809 -7.923660  -5.274928  -8.546422   
3          0.024863  ...    5.116895  0.443054  -1.879724   0.222495   
4          0.085609  ...   -6.884247 -6.812018 -12.432060 -10.807361   

     mfcc16    mfcc17    mfcc18    mfcc19     mfcc20  label  
0 -1.945349  0.523056 -2.841816 -0.065698  -0.999933  blues  
1 -1.090712  1.080965 -0.705705  1.682992  -0.814985  blues  
2  0.367640 -7.297458 -4.841222 -3.672829  -4.288005  blues  
3  1.200053 -0.744148  1.804096 -0.031980  -4.040267  blues  
4 -8.185105 -5.412588 -1.941454 -7.050840 -17.652891  blues  

[5 rows x 31 columns]

In [5]:
X = dataset.drop(['Filename','label'],axis=1) #Filename is not required
Y = dataset['label']
X

Chromagram  RootMeanSquare  LowEnergyBrightness  SpectralCentroid  \
0      0.308240        0.082484            27.461745       1530.180434   
1      0.301362        0.064603            27.914919       1175.096777   
2      0.296246        0.121445            28.715256       1300.687993   
3      0.378577        0.117733            27.093797        763.311989   
4      0.261497        0.060894            28.869262       1537.410063   
5      0.265523        0.078779            30.561682       1513.328291   
6      0.254311        0.109664            30.890941       1145.755065   
7      0.269021        0.099818            29.627338       1154.687121   
8      0.372944        0.109156            28.785792       1332.261464   
9      0.238587        0.063637            27.988616       1508.097045   
10     0.260775        0.116048            28.643808       1126.171903   
11     0.328286        0.055191            27.242355        869.493387   
12     0.234738        0.095073            29.228240       1134.259882   
13     0.226230        0.092688            28.099401       1087.604425   
14     0.310018        0.053512            28.776113        891.583190   
15     0.236322        0.056500            27.963895       1161.055562   
16     0.266695        0.057444            27.520552       1180.308840   
17     0.262490        0.072574            28.704377        852.241552   
18     0.243455        0.065755            28.426076       1250.111450   
19     0.223666        0.073543            28.123479        958.632976   
20     0.262224        0.053997            26.276840       1153.306271   
21     0.290386        0.079586            28.854573        813.019640   
22     0.272902        0.086330            29.090671        919.158776   
23     0.253112        0.079764            29.105515       1007.896387   
24     0.235386        0.069181            28.859672        857.561873   
25     0.244809        0.069095            28.000193        911.238917   
26     0.254017        0.059309            29.348840        959.108167   
27     0.266204        0.078391            30.582220       1164.396116   
28     0.245784        0.076353            28.289034        908.210821   
29     0.261466        0.112416            33.280868       1082.348083   
..          ...             ...                  ...               ...   
970    0.321252        0.039313            32.105902       2074.458410   
971    0.397564        0.098152            26.374552       1702.951819   
972    0.351510        0.124012            27.939425       1463.318433   
973    0.387420        0.113000            27.519898       1852.759048   
974    0.340014        0.115370            28.776396       1751.397454   
975    0.347508        0.080204            27.508045       1903.166515   
976    0.306034        0.113132            30.051773       1222.177457   
977    0.397017        0.087700            27.426899       1810.716846   
978    0.320641        0.111608            29.524695       1317.853823   
979    0.305343        0.083286            28.620341       1757.761396   
980    0.316282        0.073007            29.207878       2200.941927   
981    0.289125        0.065577            29.610781       2137.729397   
982    0.328576        0.062061            29.251862       2584.214743   
983    0.326889        0.077985            30.123382       1680.550892   
984    0.297545        0.078222            29.343515       2136.187730   
985    0.296341        0.051952            32.567357       1841.273305   
986    0.329008        0.048373            27.827078       2058.201684   
987    0.337058        0.125365            28.924663       2045.604115   
988    0.337486        0.055793            27.360899       2283.094143   
989    0.302035        0.079545            31.683559       1238.296377   
990    0.216348        0.127356            29.501664       2073.119839   
991    0.368251        0.079819            29.286965       2046.001540   
992    0.

In [6]:
# Scaling the data so that all the features become comparable 
scaler = StandardScaler() 
X_scaled = scaler.fit_transform(X) 
  
# Normalizing the data so that the data approximately  
# follows a Gaussian distribution 
X_normalized = normalize(X_scaled) 
  
# Converting the numpy array into a pandas DataFrame 
X_normalized = pd.DataFrame(X_normalized) 
X_normalized

0         1         2         3         4         5         6   \
0   -0.162890 -0.106672  0.086605 -0.165262 -0.147788 -0.138993 -0.046184   
1   -0.124213 -0.167916  0.090630 -0.256985 -0.102890 -0.144110  0.332896   
2   -0.138354  0.156592  0.152829 -0.192888 -0.097081 -0.211511  0.413454   
3    0.128109  0.102284  0.014594 -0.318219 -0.078230 -0.273991  0.009123   
4   -0.133277 -0.090243  0.082132 -0.045497 -0.044363 -0.103449 -0.514529   
5   -0.168953 -0.054577  0.203153 -0.067971 -0.062680 -0.150649  0.167247   
6   -0.152157  0.046727  0.170898 -0.133431 -0.052912 -0.205893 -0.317440   
7   -0.128856  0.019145  0.122167 -0.136863 -0.053858 -0.163189 -0.294861   
8    0.137275  0.080966  0.146111 -0.165228 -0.092671 -0.080604  0.313636   
9   -0.351450 -0.165124  0.092250 -0.103343 -0.091498 -0.076971  0.001296   
10  -0.217897  0.101552  0.118036 -0.214868 -0.082719 -0.301577 -0.050522   
11  -0.011925 -0.139280  0.020599 -0.245840 -0.064234 -0.206158  0.406372   
12  -0.243907  0.006077  0.128984 -0.174609 -0.068466 -0.192837  0.308828   
13  -0.311100 -0.003217  0.079301 -0.220479 -0.078142 -0.126658 -0.224836   
14  -0.053202 -0.136824  0.096797 -0.225557 -0.064353 -0.156562 -0.120550   
15  -0.269550 -0.153314  0.067586 -0.187614 -0.074779 -0.147226  0.132531   
16  -0.216411 -0.174748  0.047355 -0.212300 -0.086517 -0.130433  0.124323   
17  -0.167627 -0.073775  0.096162 -0.243431 -0.066780 -0.242970  0.109761   
18  -0.220183 -0.101310  0.084511 -0.140500 -0.065189 -0.038285  0.509489   
19  -0.299121 -0.081027  0.075907 -0.247222 -0.075761 -0.258990  0.066356   
20  -0.219466 -0.181952 -0.039505 -0.211258 -0.080427 -0.085605  0.369483   
21  -0.097897 -0.047247  0.100327 -0.245105 -0.064458 -0.217710  0.286287   
22  -0.152486 -0.026792  0.124057 -0.240386 -0.071115 -0.228784  0.088593   
23  -0.192960 -0.049129  0.118964 -0.204591 -0.067023 -0.210680  0.060735   
24  -0.214042 -0.079171  0.096221 -0.223350 -0.061502 -0.217266  0.156114   
25  -0.201976 -0.082967  0.057329 -0.219235 -0.064055 -0.208762 -0.296865   
26  -0.175242 -0.112678  0.121108 -0.200253 -0.062129 -0.177897  0.339720   
27  -0.169930 -0.056920  0.207553 -0.170087 -0.071067 -0.217951 -0.050537   
28  -0.198698 -0.057917  0.071454 -0.218871 -0.063662 -0.231174 -0.005413   
29  -0.158969  0.062791  0.312740 -0.169355 -0.061563 -0.050914 -0.082769   
..        ...       ...       ...       ...       ...       ...       ...   
970 -0.029861 -0.202255  0.288790  0.092228 -0.057694  0.054807 -0.084324   
971  0.267397  0.029257 -0.044118 -0.023168 -0.082814  0.050979 -0.254418   
972  0.090870  0.226017  0.117649 -0.163107 -0.120438 -0.021636 -0.044877   
973  0.221390  0.119135  0.059302  0.046984 -0.077149  0.082634 -0.001785   
974  0.032392  0.154894  0.199385 -0.000246 -0.106226  0.043609  0.382057   
975  0.057864 -0.079609  0.057594  0.069674 -0.072982  0.142591  0.102682   
976 -0.119661  0.129603  0.309300 -0.266498 -0.117501 -0.198507 -0.042646   
977  0.238317 -0.031897  0.046616  0.025069 -0.070750  0.089851 -0.209903   
978 -0.043511  0.094176  0.203390 -0.171973 -0.089686 -0.043524  0.139639   
979 -0.106305 -0.057800  0.147848  0.002576 -0.078827 -0.020079  0.251307   
980 -0.063108 -0.113837  0.192849  0.191482 -0.047517  0.110016 -0.063388   
981 -0.150458 -0.141915  0.206515  0.150398 -0.034964  0.031495  0.187819   
982 -0.012866 -0.131058  0.147252  0.266008  0.002585  0.143243 -0.006463   
983 -0.026409 -0.096860  0.301528 -0.034206 -0.095860  0.027413 -0.125260   
984 -0.127317 -0.081065  0.195081  0.156721 -0.051258  0.109578  0.219384   
985 -0.125699 -0.211163  0.427977  0.034823 -0.081840 -0.048749 -0.008654   
986 -0.018427 -0.297562  0.094212  0.154761 -0.051926  0.026005 -0.378578   
987  0.011295  0.138363  0.131821  0.097347 -0.052106  0.039242  0.237570   
988  0.014681 -0.190934  0.037546  0.206151 -0.013122 -0.000038 -0.013871   
989 -0.123278 -0.081998  0.419628 -0.232007 -0.106404 -0.249218  0.111663   
990 -0.

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_normalized, Y, test_size=0.10)

In [8]:
from sklearn.svm import SVC
#Classifying normalised data using SVM
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [9]:
y_pred = svclassifier.predict(X_test)

In [10]:
print(confusion_matrix(Y_test,y_pred))
print(classification_report(Y_test,y_pred))

[[ 8  0  0  0  0  1  1  0  0  1]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 1  0  6  0  0  0  0  0  0  1]
 [ 0  0  0  9  1  0  0  0  0  0]
 [ 0  0  1  2  7  1  3  2  0  0]
 [ 1  1  0  0  0  1  0  0  0  0]
 [ 0  0  0  1  0  0  9  0  0  0]
 [ 0  0  0  0  0  0  0  7  0  0]
 [ 0  0  1  2  0  0  0  0  8  0]
 [ 1  0  1  0  2  1  4  0  0  4]]
              precision    recall  f1-score   support

       blues       0.73      0.73      0.73        11
   classical       0.92      1.00      0.96        11
     country       0.67      0.75      0.71         8
       disco       0.64      0.90      0.75        10
      hiphop       0.70      0.44      0.54        16
        jazz       0.25      0.33      0.29         3
       metal       0.53      0.90      0.67        10
         pop       0.78      1.00      0.88         7
      reggae       1.00      0.73      0.84        11
        rock       0.67      0.31      0.42        13

    accuracy                           0.70       100
   macro avg       